// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcFAMgmVQXTNf3vEr0kQwrVT_43VYZGAY',
    appId: '1:209418664792:web:3bbd1c5fc98be0a2c1032d',
    messagingSenderId: '209418664792',
    projectId: 'todolist-vinicius2405',
    authDomain: 'todolist-vinicius2405.firebaseapp.com',
    storageBucket: 'todolist-vinicius2405.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-bhOWt-p1GVzD2nRinA1iiBHYOt7RIlA',
    appId: '1:209418664792:android:e1c6e6225233c337c1032d',
    messagingSenderId: '209418664792',
    projectId: 'todolist-vinicius2405',
    storageBucket: 'todolist-vinicius2405.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnP_HyoOQrZM3XN-_uyj22OXRnvFHSpAM',
    appId: '1:209418664792:ios:61935f36383b2a3fc1032d',
    messagingSenderId: '209418664792',
    projectId: 'todolist-vinicius2405',
    storageBucket: 'todolist-vinicius2405.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnP_HyoOQrZM3XN-_uyj22OXRnvFHSpAM',
    appId: '1:209418664792:ios:61935f36383b2a3fc1032d',
    messagingSenderId: '209418664792',
    projectId: 'todolist-vinicius2405',
    storageBucket: 'todolist-vinicius2405.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcFAMgmVQXTNf3vEr0kQwrVT_43VYZGAY',
    appId: '1:209418664792:web:c9257579144bd5f0c1032d',
    messagingSenderId: '209418664792',
    projectId: 'todolist-vinicius2405',
    authDomain: 'todolist-vinicius2405.firebaseapp.com',
    storageBucket: 'todolist-vinicius2405.firebasestorage.app',
  );
}
